### PR TITLE
Google calendars

### PR DESCRIPTION
**Pull request by Naokimi**
**Purpose**
integrating google calendar so that when we implement recurring events we can avoid creating event on slot where you already have something scheduled

**How to test**
1. create Calendar(s) using .ics url (Google calendar -> settings menu -> settings -> settings for my calendar -> Public address in iCal format) and your user
image
2. run script `rails runner script/temp/20201118_test_calendar_reader.rb`
The script will create availability in the same time as your calendar events (the opposite of what we want to implement, but as I said, this is just for testing)

### CODE REVIEW

**Comment by JupitersLB** [comment]
@Naokimi Having issues getting the test script to work.

`sort': comparison of Icalendar::Values::DateTime with ActiveSupport::TimeWithZone failed (ArgumentError)

My guess is it is this:

`@events << event if event.dtstart > @start_time && event.dtstart < @end_time`

**Comment by Naokimi** [comment]
@JupitersLB Weird I just tried rerunning the script on my machine and didn't get that error.
Can we setup a time and look at it together?

**Review by JupitersLB — COMMENTED** [review]
Works much better. Only things that don't appear now are things scheduled for at 45 min mark.

**Comment by Naokimi** [comment]
you mean like if you have an event from 10:45 to 11:30 it doesn't appear at all or it appears only for the 11:00-11:30 block?

**Comment by JupitersLB** [comment]
I only have something like 10:45 to 11:15. Things similar to that don't appear.

**Comment by Naokimi** [comment]
ok, in this case I suppose you'd want to block 10:30-11:30 right?
will look into it

**Comment by JupitersLB** [comment]
I think that would be the best solution.

**Comment by Naokimi** [comment]
@JupitersLB I added an uneven event but seems like my iCal doesn't update even after an hour
can you please try it on your end?

**Comment by Naokimi** [comment]
@JupitersLB fixed the bug, please review

**Comment by JupitersLB** [comment]
@Naokimi Shows up for an hour block 👌

**Comment by Naokimi** [comment]
@JupitersLB feel free to leave a review and merge :)

**Review by JupitersLB — APPROVED** [review]

**Pull request merged**
